src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Timestampable;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?Basket $basket = null;

    #[ORM\Column(nullable: true)]
    private ?int $quantity = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?Pizza $pizza = null;

    #[Timestampable(on: "create")]
    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $createdAt = null;

    #[Timestampable(on: "update")]
    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updatedAt = null;

    #[ORM\ManyToMany(targetEntity: Order::class, mappedBy: 'articles')]
    private Collection $orders;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBasket(): ?Basket
    {
        return $this->basket;
    }

    public function setBasket(?Basket $basket): self
    {
        $this->basket = $basket;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPizza(): ?Pizza
    {
        return $this->pizza;
    }

    public function setPizza(?Pizza $pizza): self
    {
        $this->pizza = $pizza;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getTotal(): float
    {
        return round($this->quantity * $this->getPizza()->getPrice(), 2);
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->addArticle($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            $order->removeArticle($this);
        }

        return $this;
    }
}

src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Timestampable;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?User $user = null;

    #[ORM\ManyToMany(targetEntity: Article::class, inversedBy: 'orders')]
    private Collection $articles;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Address $address = null;

    #[Timestampable(on: "create")]
    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $createdAt = null;

    #[Timestampable(on: "update")]
    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updatedAt = null;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        $this->articles->removeElement($article);

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(?Address $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

src/Controller/Front/BasketController.php
<?php

namespace App\Controller\Front;

use App\Entity\Pizza;
use App\Entity\Article;
use App\Repository\BasketRepository;
use App\Repository\ArticleRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[IsGranted("ROLE_USER")]
#[Route("/mon-panier")]
class BasketController extends AbstractController
{
    #[Route('/', name: 'app_front_basket_display')]
    public function display(): Response
    {
        return $this->render('front/basket/display.html.twig');
    }

    #[Route("/{id}/ajouter", name: "app_front_basket_addArticle")]
    public function addArticle(BasketRepository $repository, Pizza $pizza): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        $basket = $user->getBasket();

        $article = new Article();
        $article->setQuantity(1);
        $article->setBasket($basket);
        $article->setPizza($pizza);

        $basket->addArticle($article);

        $repository->add($basket, true);

        return $this->redirectToRoute("app_front_basket_display");
    }

    #[Route("/{id}/supprimer", name: "app_front_basket_deleteArticle")]
    public function deleteArticle(BasketRepository $basketRepo, ArticleRepository $articleRepo, int $id): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        $basket = $user->getBasket();

        $articleToDelete = $articleRepo->find($id);

        $basket->removeArticle($articleToDelete);

        $basketRepo->add($basket, true);

        return $this->redirectToRoute("app_front_basket_display");
    }

    #[Route("/{id}/plus", name: "app_front_basket_increase")]
    public function increase(Article $article, ArticleRepository $repository): Response
    {
        $article->setQuantity(($article->getQuantity() + 1));
        $repository->add($article, true);

        return $this->redirectToRoute("app_front_basket_display");
    }

    #[Route("/{id}/moins", name: "app_front_basket_decrease")]
    public function decrease(Article $article, ArticleRepository $articleRepo, BasketRepository $basketRepo): Response
    {
        if ($article->getQuantity() <= 1) {
            /** @var User $user */
            $user = $this->getUser();
            $user->getBasket()->removeArticle($article);

            $basketRepo->add($user->getBasket(), true);
        } else {
            $article->setQuantity($article->getQuantity() - 1);
            $articleRepo->add($article, true);
        }

        return $this->redirectToRoute("app_front_basket_display");
    }
}

src/Controller/Front/HomeController.php
<?php

namespace App\Controller\Front;

use App\Repository\PizzaRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

// #[IsGranted("ROLE_USER")]
class HomeController extends AbstractController
{
    #[Route('/accueil', name: 'app_front_home_index')]
    public function index(PizzaRepository $repository): Response
    {
        $pizzas = $repository->findAll();

        return $this->render('front/home/index.html.twig', [
            'pizzas' => $pizzas
        ]);
    }
}

src/Controller/Front/OrderController.php
<?php

namespace App\Controller\Front;

use App\DTO\Payment;
use App\Entity\User;
use App\Entity\Order;
use App\Form\PaymentType;
use App\Repository\OrderRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[IsGranted("ROLE_USER")]
#[Route("/commander")]
class OrderController extends AbstractController
{
    #[Route('/', name: 'app_front_order_display')]
    public function display(Request $request, OrderRepository $repository): Response
    {
        /** @var User $user */
        $user = $this->getUser();

        $payment = new Payment();
        $payment->address = $user->getAddress();

        $form = $this->createForm(PaymentType::class, $payment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $order = new Order();
            $order->setUser($user);
            $order->setAddress($payment->address);

            foreach ($user->getBasket()->getArticles() as $article) {
                $order->addArticle($article);
            }

            $repository->add($order, true);

            return $this->redirectToRoute("app_front_order_validate", [
                "id" => $order->getId()
            ]);
        }

        return $this->render('front/order/display.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route("/{id}/validation", name: "app_front_order_validate")]
    public function validate(Order $order): Response
    {
        return $this->render("front/order/validate.html.twig", [
            "order" => $order
        ]);
    }
}

templates/front/order/display.html.twig
{% extends 'base.html.twig' %}

{% block title %}PizzaShop - Commander{% endblock %}

{% block body %}

    <h1>Passer la commande</h1>

    <ul>
        {% for article in app.user.basket.articles %}
            <li>{{ article.quantity }} <i class="fa-solid fa-xmark"></i> {{ article.pizza.name }} <i class="fa-solid fa-equals"></i> {{ article.total }} €</li>
        {% endfor %}
    </ul>


    <form method="post">

        {{ form_start(form) }}

        <h3>Vos coordonnées</h3>
        <div class="form-content">
            <div class="form-group">
                <div class="form-group-errors">
                    {{ form_errors(form.address.city) }}
                </div>
                <div class="form-group-row">
                    {{ form_label(form.address.city) }}
                    {{ form_widget(form.address.city) }}
                </div>
            </div>
            <div class="form-group">
                <div class="form-group-errors">
                    {{ form_errors(form.address.zipCode) }}
                </div>
                <div class="form-group-row">
                    {{ form_label(form.address.zipCode) }}
                    {{ form_widget(form.address.zipCode) }}
                </div>
            </div>
            <div class="form-group">
                <div class="form-group-errors">
                    {{ form_errors(form.address.street) }}
                </div>
                <div class="form-group-row">
                    {{ form_label(form.address.street) }}
                    {{ form_widget(form.address.street) }}
                </div>
            </div>
            <div class="form-group">
                <div class="form-group-errors">
                    {{ form_errors(form.address.supplement) }}
                </div>
                <div class="form-group-row">
                    {{ form_label(form.address.supplement) }}
                    {{ form_widget(form.address.supplement) }}
                </div>
            </div>
        </div>

        <div class="price-container">
            <h2>Total : {{ app.user.basket.total}} €</h2>
        </div>

        <div class="form-content">

            <div class="form-group">
                <div class="form-group-errors">
                    {{ form_errors(form.cardNumber)}}
                </div>
                <div class="form-group-row">
                    {{ form_label(form.cardNumber)}}
                    {{ form_widget(form.cardNumber)}}
                </div>
            </div>
            <div class="last-row">
                <div class="form-group-expiration_date">
                    <div class="form-group-errors">
                        {{ form_errors(form.expirationMonth)}}
                        {{ form_errors(form.expirationYear)}}
                    </div>
                    <div class="form-group-row">
                        {{ form_label(form.expirationMonth)}}
                        {{ form_widget(form.expirationMonth)}}
                        {{ form_widget(form.expirationYear)}}
                    </div>
                </div>
                <div class="form-group-cvc">
                    <div class="form-group-errors">
                        {{ form_errors(form.cvc)}}
                    </div>
                    <div class="form-group-row">
                        {{ form_label(form.cvc)}}
                        {{ form_widget(form.cvc)}}
                    </div>
                </div>
            </div>
            <div class="btn-container">
                <button type="submit" class="btn btn-success">
                <i class="fa-solid fa-credit-card"></i>
                <span>Payer</span>
                </button>
            </div>
        
        </div>

        <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}">

    {{ form_end(form) }}
    
    </form>

{% endblock %}

templates/front/order/validate.html.twig
{% extends "base.html.twig" %}

{% block title %}PizzaShop - Confirmation de la commande{% endblock %}

{% block body %}

<h1>Confirmation</h1>

<p style="text-align: center; line-height: 30px; padding-top: 0.6rem;">
  Votre commande a bien été enregistrée et vous sera délivrée sous peu <i class="fa-solid fa-face-grin-wink"></i><br>
  Merci et bon apétit !
</p>

<div class="check-container">
  <div class="circle circle-bigger">
    <div class="circle circle-smaller"></div>
  <i class="fa-solid fa-check"></i>
  </div>
</div>

<div class="btn-container">
  <a href="{{ path("app_front_home_index") }}" class="btn btn-success">
    <i class="fa-solid fa-circle-arrow-left"></i>
    <span>Retour à l'accueil</span>
  </a>
</div>

{% endblock %}